### ISSUE TITLE
Disabling telemetry doesn't take effect until restart occurs

### ISSUE THREAD

**Issue by Charles-Gagnon** [dzsquared/demo-mode#3]
If telemetry is disabled it won't take effect until the app is restarted. It's generally considered good practice to have settings changes immediately take effect (especially for things such as telemetry)

You can use the [onDidChangeConfiguration](https://github.com/microsoft/azuredatastudio/blob/master/src/vs/vscode.d.ts#L8242) event to listen for settings changes, an example of doing so is here :

https://github.com/microsoft/azuredatastudio/blob/master/src/sql/platform/queryHistory/common/queryHistoryServiceImpl.ts#L44

(you can also just query the settings every time you want to send an event to get the current value, such as you do here https://github.com/dzsquared/demo-mode/blob/master/src/extension.ts#L34)

**Comment by dzsquared** [comment]
@Charles-Gagnon thanks for the help!  I'll get the new release over to ADS soon.

I've updated my initial blog post about the telemetry implementation with credit to your suggestion: https://www.drewsk.tech/2019/11/20/how-to-add-telemetry-to-an-azure-data-studio-extension/

I've also stumbled across ads-extension-telemetry now too (https://github.com/Charles-Gagnon/ads-extension-telemetry), so will do a writeup about the additional capability that it provides at a later date

**Comment by Charles-Gagnon** [comment]
Nice 😄 I haven't done much with that extension lately but it's similar to what we use in core ADS so hopefully provides some use to you! Definitely let me know if you have any suggestions for things you'd like to see for it!
